### ISSUE TITLE
Gunicorn does not started

### ISSUE THREAD

**Issue by merryech0** [Tinche/bower-cache#2]
```
(bower-cache)user@host /tmp/bower-cache$ bower-cache-init ./app
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/widgets.css'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/dashboard.css'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/login.css'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/base.css'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/changelists.css'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/forms.css'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/rtl.css'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/css/ie.css'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/core.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/LICENSE-JQUERY.txt'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/prepopulate.min.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/calendar.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/inlines.min.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/SelectBox.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/collapse.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/inlines.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/collapse.min.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/actions.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/prepopulate.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/timeparse.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/jquery.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/actions.min.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/SelectFilter2.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/jquery.min.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/jquery.init.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/urlify.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/js/admin/DateTimeShortcuts.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_calendar.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/tooltag-arrowright_over.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/selector-icons.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/tool-right.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/default-bg.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_clock.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/chooser_stacked-bg.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-unknown.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/inline-delete.png'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/changelist-bg_rtl.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/tooltag-add.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_searchbox.png'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/tool-left_over.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_changelink.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/inline-splitter-bg.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/tool-left.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/tooltag-add_over.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/inline-restore-8bit.png'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/nav-bg-reverse.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-no.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/nav-bg.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/tool-right_over.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/chooser-bg.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_addlink.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_alert.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/default-bg-reverse.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_success.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/tooltag-arrowright.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_error.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/inline-restore.png'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon_deletelink.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/deleted-overlay.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/nav-bg-selected.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/changelist-bg.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/nav-bg-grabber.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/icon-yes.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/inline-delete-8bit.png'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/selector-search.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/sorting-icons.gif'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_on.png'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/django/contrib/admin/static/admin/img/gis/move_vertex_off.png'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/css/prettify.css'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/css/bootstrap-tweaks.css'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/css/default.css'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/css/bootstrap.min.css'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/bootstrap.min.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/jquery-1.8.1-min.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/prettify-min.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/js/default.js'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/img/glyphicons-halflings-white.png'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/img/grid.png'
Copying '/tmp/bower-cache/local/lib/python2.7/site-packages/rest_framework/static/rest_framework/img/glyphicons-halflings.png'

80 static files copied to '/tmp/bower-cache/app/static'.
Creating tables ...
Creating table auth_permission
Creating table auth_group_permissions
Creating table auth_group
Creating table auth_user_groups
Creating table auth_user_user_permissions
Creating table auth_user
Creating table django_admin_log
Creating table django_content_type
Creating table django_session
Creating table celery_taskmeta
Creating table celery_tasksetmeta
Creating table djcelery_intervalschedule
Creating table djcelery_crontabschedule
Creating table djcelery_periodictasks
Creating table djcelery_periodictask
Creating table djcelery_workerstate
Creating table djcelery_taskstate
Creating table djkombu_queue
Creating table djkombu_message
Creating table registry_package
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Superuser created successfully.
(bower-cache)user@host /tmp/bower-cache$ cd app
(bower-cache)user@host /tmp/bower-cache/app$ python manage.py changepassword admin
Changing password for user 'admin'
Password: 
Password (again): 
Password changed successfully for user 'admin'
(bower-cache)user@host /tmp/bower-cache/app$ gunicorn bowercachesite:wsgi
Failed to find application: 'bowercachesite'
Traceback (most recent call last):
  File "/tmp/bower-cache/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/tmp/bower-cache/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/tmp/bower-cache/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 185, in run
    super(Application, self).run()
  File "/tmp/bower-cache/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
  File "/tmp/bower-cache/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 169, in run
    self.manage_workers()
  File "/tmp/bower-cache/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 477, in manage_workers
    self.spawn_workers()
  File "/tmp/bower-cache/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 542, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/tmp/bower-cache/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 209, in handle_chld
    self.reap_workers()
  File "/tmp/bower-cache/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 462, in reap_workers
    raise HaltServer(reason, self.APP_LOAD_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 4>
```

**Comment by Tinche** [comment]
Sorry, that was a typo in the instructions. The command is:

<pre>
gunicorn bowercachesite.wsgi
</pre>

("." instead of ":")

**Comment by merryech0** [comment]
Thanks
